export const Path = {
    dashboard : '/dashboard',
    salesDetails : '/transaction/sales_details',
    purchaseDetails : '/transaction/purchase_details',
    boxDetails : '/transaction/box_details',
    advanceOrder : '/transaction/advance_order',
    ledgerAccount : '/master/ledger_account',
    productRegister : '/master/product_register',
    masterDetails : '/master/master_details',
    balanceEnquiry : '/balance_enquiry',
    customerBalance : '/balance_enquiry/customer_balance',
    supplierBalance : '/balance_enquiry/supplier_balance',
    reports : '/reports',
    productReports : '/reports/product_reports',
    customerReports : '/reports/customer_reports',
    supplierReports : '/reports/supplier_reports',
    boxBalanceReports : '/reports/box_balance_reports',
    paymentIndex : '/paymentRecipt',
    incomeDetails : '/income_details',
    expenseDetails : '/expense_details',
    periodicStatement : '/periodic_statement',
    periodicStatementGoTable : "/periodic_statement/periodic_statement_table",
    vehicleExpenses : '/vehicle_expenses',
    vehicleExpensesEdit : '/vehicle_expenses/:i',
    vehicleExpensesGoTable : '/vehicle_expenses/vehicle_expenses_table',
    commonExpenses : '/common_expenses',
    commonExpensesEdit:'/common_expenses/:i',
    commonExpensesGoTable : '/common_expenses/common_expenses_table',
    notes : '/notes',
    quotation : '/quotation',
    quotationEdit : '/quotation/:i',
    quotationGoTable : '/quotation/quotation_table',
    quotationGoTableEdit : '/quotation/quotation_table/:i',
    quotationSubmitTable:"/quotation/quotation_Submit_table",
    quotationSubmitTableEdit:"/quotation/quotation_Submit_table/:i",
    ProductQuotation:"/quotation/quotation_Product_table",
    ProductQuotationDetails:"/quotation/quotation_Product_table/:i",
    notesTextPage:"/notes_text_page",
    notesEditPage:"/notes_text_page/:id",
    salesDetailsLocate : "/sales_details/transation_sales_details"
}