export const emptyArray = [
    {
        ProductId:"",
        ProductName:"",
        Mark:"",
        Quantity:"",
        Rate:"",
        TotalAmount:""
    },
    {
        ProductId:"",
        ProductName:"",
        Mark:"",
        Quantity:"",
        Rate:"",
        TotalAmount:""
    },
    {
        ProductId:"",
        ProductName:"",
        Mark:"",
        Quantity:"",
        Rate:"",
        TotalAmount:""
    },
    {
        ProductId:"",
        ProductName:"",
        Mark:"",
        Quantity:"",
        Rate:"",
        TotalAmount:""
    },
]