export const SupplierPurchaseArray = [
    {
        Sno : "1",
        BillNo : "1234567890",
        SupplierName : "Vignesh",
        ProductName : "Tomato",
        ProductQuantity : "3",
        Rate : "100",
        TotalAmount : "1000",
        TotalItems : "50",
        NetAmount : "1",
        PreviousAmount : "1000",
        NetBalance : "2000",
        CashReceived : "2000"
    },
    {
        Sno : "1",
        BillNo : "1234567890",
        SupplierName : "Vignesh",
        ProductName : "Tomato",
        ProductQuantity : "3",
        Rate : "100",
        TotalAmount : "1000",
        TotalItems : "50",
        NetAmount : "1",
        PreviousAmount : "1000",
        NetBalance : "2000",
        CashReceived : "2000"
    },
    {
        Sno : "1",
        BillNo : "1234567890",
        SupplierName : "Vignesh",
        ProductName : "Tomato",
        ProductQuantity : "3",
        Rate : "100",
        TotalAmount : "1000",
        TotalItems : "50",
        NetAmount : "1",
        PreviousAmount : "1000",
        NetBalance : "2000",
        CashReceived : "2000"
    },
    {
        Sno : "1",
        BillNo : "1234567890",
        SupplierName : "Vignesh",
        ProductName : "Tomato",
        ProductQuantity : "3",
        Rate : "100",
        TotalAmount : "1000",
        TotalItems : "50",
        NetAmount : "1",
        PreviousAmount : "1000",
        NetBalance : "2000",
        CashReceived : "2000"
    },
    {
        Sno : "1",
        BillNo : "1234567890",
        SupplierName : "Vignesh",
        ProductName : "Tomato",
        ProductQuantity : "3",
        Rate : "100",
        TotalAmount : "1000",
        TotalItems : "50",
        NetAmount : "1",
        PreviousAmount : "1000",
        NetBalance : "2000",
        CashReceived : "2000"
    },
    {
        Sno : "1",
        BillNo : "1234567890",
        SupplierName : "Vignesh",
        ProductName : "Tomato",
        ProductQuantity : "3",
        Rate : "100",
        TotalAmount : "1000",
        TotalItems : "50",
        NetAmount : "1",
        PreviousAmount : "1000",
        NetBalance : "2000",
        CashReceived : "2000"
    },
    {
        Sno : "1",
        BillNo : "1234567890",
        SupplierName : "Vignesh",
        ProductName : "Tomato",
        ProductQuantity : "3",
        Rate : "100",
        TotalAmount : "1000",
        TotalItems : "50",
        NetAmount : "1",
        PreviousAmount : "1000",
        NetBalance : "2000",
        CashReceived : "2000"
    },
    {
        Sno : "1",
        BillNo : "1234567890",
        SupplierName : "Vignesh",
        ProductName : "Tomato",
        ProductQuantity : "3",
        Rate : "100",
        TotalAmount : "1000",
        TotalItems : "50",
        NetAmount : "1",
        PreviousAmount : "1000",
        NetBalance : "2000",
        CashReceived : "2000"
    },
    {
        Sno : "1",
        BillNo : "1234567890",
        SupplierName : "Vignesh",
        ProductName : "Tomato",
        ProductQuantity : "3",
        Rate : "100",
        TotalAmount : "1000",
        TotalItems : "50",
        NetAmount : "1",
        PreviousAmount : "1000",
        NetBalance : "2000",
        CashReceived : "2000"
    },
    {
        Sno : "1",
        BillNo : "1234567890",
        SupplierName : "Vignesh",
        ProductName : "Tomato",
        ProductQuantity : "3",
        Rate : "100",
        TotalAmount : "1000",
        TotalItems : "50",
        NetAmount : "1",
        PreviousAmount : "1000",
        NetBalance : "2000",
        CashReceived : "2000"
    },
]