import Tomato from "../../assets/ProductDeteils/tomato.png"; 
export const DummyArray=[
       { 
        image:Tomato,
        productName : 'Tomato',
        totalStock:"Total Stock :",
        totalQuantity:100,
        totalUnit:"kg",
        availableStock:"Available Stock :",
        availableQuantity:100,
        availableUnit:"kg",
        pricePerStock:"Price Per Stock :",
        pricePerQuantity:100,
        pricePerUnit:"kg"
       }
       ,
       { 
        image:Tomato,
        productName : 'Tomato',
        totalStock:"Total Stock :",
        totalQuantity:100,
        totalUnit:"kg",
        availableStock:"Available Stock :",
        availableQuantity:100,
        availableUnit:"kg",
        pricePerStock:"Price Per Stock :",
        pricePerQuantity:100,
        pricePerUnit:"kg"
       },
       { 
              image:Tomato,
              productName : 'Tomato',
              totalStock:"Total Stock :",
              totalQuantity:100,
              totalUnit:"kg",
              availableStock:"Available Stock :",
              availableQuantity:100,
              availableUnit:"kg",
              pricePerStock:"Price Per Stock :",
              pricePerQuantity:100,
              pricePerUnit:"kg"
             },
             { 
              image:Tomato,
              productName : 'Tomato',
              totalStock:"Total Stock :",
              totalQuantity:100,
              totalUnit:"kg",
              availableStock:"Available Stock :",
              availableQuantity:100,
              availableUnit:"kg",
              pricePerStock:"Price Per Stock :",
              pricePerQuantity:100,
              pricePerUnit:"kg"
             },
             { 
              image:Tomato,
              productName : 'Tomato',
              totalStock:"Total Stock :",
              totalQuantity:100,
              totalUnit:"kg",
              availableStock:"Available Stock :",
              availableQuantity:100,
              availableUnit:"kg",
              pricePerStock:"Price Per Stock :",
              pricePerQuantity:100,
              pricePerUnit:"kg"
             },
             { 
              image:Tomato,
              productName : 'Tomato',
              totalStock:"Total Stock :",
              totalQuantity:100,
              totalUnit:"kg",
              availableStock:"Available Stock :",
              availableQuantity:100,
              availableUnit:"kg",
              pricePerStock:"Price Per Stock :",
              pricePerQuantity:100,
              pricePerUnit:"kg"
             },
             { 
              image:Tomato,
              productName : 'Tomato',
              totalStock:"Total Stock :",
              totalQuantity:100,
              totalUnit:"kg",
              availableStock:"Available Stock :",
              availableQuantity:100,
              availableUnit:"kg",
              pricePerStock:"Price Per Stock :",
              pricePerQuantity:100,
              pricePerUnit:"kg"
             },
             { 
              image:Tomato,
              productName : 'Tomato',
              totalStock:"Total Stock :",
              totalQuantity:100,
              totalUnit:"kg",
              availableStock:"Available Stock :",
              availableQuantity:100,
              availableUnit:"kg",
              pricePerStock:"Price Per Stock :",
              pricePerQuantity:100,
              pricePerUnit:"kg"
             },
             { 
              image:Tomato,
              productName : 'Tomato',
              totalStock:"Total Stock :",
              totalQuantity:100,
              totalUnit:"kg",
              availableStock:"Available Stock :",
              availableQuantity:100,
              availableUnit:"kg",
              pricePerStock:"Price Per Stock :",
              pricePerQuantity:100,
              pricePerUnit:"kg"
             },
             { 
              image:Tomato,
              productName : 'Tomato',
              totalStock:"Total Stock :",
              totalQuantity:100,
              totalUnit:"kg",
              availableStock:"Available Stock :",
              availableQuantity:100,
              availableUnit:"kg",
              pricePerStock:"Price Per Stock :",
              pricePerQuantity:100,
              pricePerUnit:"kg"
             },
             { 
              image:Tomato,
              productName : 'Tomato',
              totalStock:"Total Stock :",
              totalQuantity:100,
              totalUnit:"kg",
              availableStock:"Available Stock :",
              availableQuantity:100,
              availableUnit:"kg",
              pricePerStock:"Price Per Stock :",
              pricePerQuantity:100,
              pricePerUnit:"kg"
             },
]