export const VehicleExpenseDeteil=[
    {
        Name:"Date",
        type:"date",
        title:"Date",
        disable:true
    },
    {
        Name:"Vehicle Number",
        type:"number",
        title:"VehicleNumber",
        disable:false
    },
    {
        Name:"Name", 
        type:"text",
        title:"Name",
        disable:false
    },
    {
        Name:"Amount",
        type:"number",
        title:"Amount",
        disable:false
    },
    {
        Name:"Expense Reason",
        type:"text",
        title:"ExpenseReason",
        disable:false
    }
]

export const VehicleExpenseTableDetail=[
    {
        SNo:1,
        VehicleNumber:"1234567890",
        Name:"vickey",
        ExpenseReason:"abcdef",
        ExpenseAmount:10000,
        Date:"20/02/2024"
    },
    {
        SNo:1,
        VehicleNumber:"1234567890",
        Name:"vickey",
        ExpenseReason:"abcdef",
        ExpenseAmount:10000,
        Date:"20/02/2024"
    },
    {
        SNo:1,
        VehicleNumber:"1234567890",
        Name:"vickey",
        ExpenseReason:"abcdef",
        ExpenseAmount:10000,
        Date:"20/02/2024"
    },
    {
        SNo:1,
        VehicleNumber:"1234567890",
        Name:"vickey",
        ExpenseReason:"abcdef",
        ExpenseAmount:10000,
        Date:"20/02/2024"
    },
]